# builds and publishes on tag pushes
name: Release docker image
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '**.md'

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tagged Image
        run: |
          echo "Building image cyclonecouriers/vroom-docker:${{ steps.tag.outputs.TAG }}"
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag cyclonecouriers/vroom-docker:${{ steps.tag.outputs.TAG }} .
